### ISSUE TITLE
fatal error: module 'app_settings' not found

### ISSUE THREAD

**Issue by rjkolli7** [spencerccf/app_settings#120]
Am using Macbook with M1 chip.. 

Got this error when running `flutter run ios`

> ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'app_settings' not found
               @import app_settings;
                ~~~~~~~^~~~~~~~~~~~
               1 error generated.


`flutter doctor -v`

[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 11.2.3 20D91 darwin-arm, locale en-IN)
    • Flutter version 2.9.0-0.1.pre at /Users/rajeshkolli/Library/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (8 weeks ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at /Users/rajeshkolli/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 02ADA7AF-DE26-4C5F-BFF8-A65626C67730 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 98.0.4758.80

! Doctor found issues in 1 category.


Full Error:

 fatal error:
module
               'app_settings' not found
               @import app_settings;
                ~~~~~~~^~~~~~~~~~~~
               1 error generated.
           
           
[ +832 ms] Could not build the application for the simulator.
[   +9 ms] Error launching application on iPhone 12 Pro Max.
[  +12 ms] "flutter run" took 61,102ms.
[  +24 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:684:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +265 ms] ensureAnalyticsSent: 260ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by flutter-clutter** [comment]
Exactly the same issue. Also using a Macbook with M1 chip.

Precisely, it occurs whenever I execute 

```
flutter build ipa --release
```

which is exactly what is executed in my CI-pipeline. Unfortunately this leaves me unable to build my project.
In the pipeline, a Mac Mini is used so I guess it has nothing to do with the architecture.

**Comment by chinzorigts** [comment]
Me too. Exactly the same issue. I am using Macbook Pro 2017.

**Comment by plinkos** [comment]
I see you are using Flutter beta channel… beta may not be totally ready yet.  Try stable channel. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by javieritis** [comment]
any solution?

**Comment by josephmangmang** [comment]
same error here :(

**Comment by plinkos** [comment]
Please try latest pub.dev version: 4.1.3

**Comment by palmsnipe** [comment]
Same issue there with the version 4.1.5. I am targeting iOS 12.0.
```
Failed to build iOS app
Error output from Xcode build:
↳
    2022-04-12 23:26:17.239 xcodebuild[46259:853636] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-04-12 23:26:17.239 xcodebuild[46259:853636] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/0c/g25vt6c17fd2nwcy5qy5c32m0000gn/T/flutter_tools.vyzedu/flutter_ios_build_temp_dirWUCLKb/temporary_xcresult_bundle

    /Users/user/project/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'app_settings' not found
    @import app_settings;
     ~~~~~~~^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
        /var/folders/0c/g25vt6c17fd2nwcy5qy5c32m0000gn/T/flutter_tools.vyzedu/flutter_ios_build_temp_dirWUCLKb/temporary_xcresult_bundle


Parse Issue (Xcode): Module 'app_settings' not found
/Users/user/project/Runner/GeneratedPluginRegistrant.m:11:8
```

**Comment by horo99** [comment]
I'm stuck in the same question

**Comment by horo99** [comment]
I know the problem, and I have solved it. 
It doesn't matter whether this plugin is used, but iOS version in pod file does matche with deployment info in Xcode.

https://stackoverflow.com/questions/61956166/flutter-module-not-found-in-xcode

**Comment by superorange** [comment]
> 我知道这个问题，我已经解决了。 是否使用此插件无关紧要，但 pod 文件中的 iOS 版本确实与 Xcode 中的部署信息匹配。
> 
> https://stackoverflow.com/questions/61956166/flutter-module-not-found-in-xcode

感谢，正解
