### ISSUE TITLE
Not working on Android 13

### ISSUE THREAD

**Issue by Karmalakas** [spencerccf/app_settings#164]
When calling `AppSettings.openBluetoothSettings()` I get
```
E/flutter (10087): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method bluetooth on channel app_settings)
E/flutter (10087): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
E/flutter (10087): <asynchronous suspension>
E/flutter (10087): #1      AppSettings.openBluetoothSettings (package:app_settings/app_settings.dart:57:5)
E/flutter (10087): <asynchronous suspension>
```

**Comment by Karmalakas** [comment]
After I reconnected the device and freshly recompiled, it now opens device pairing list also. Closing this issue, because error is gone (still wrong page)
