### ISSUE TITLE
Opening OS system settings

### ISSUE THREAD

**Issue by ced1check** [spencerccf/app_settings#204]
Anyway to open system settings, at first I though this plugin would allow that, however it only opens app's settings page itself.

There is a plugin system_settings that can do that however it's too old to be used anymore:
https://github.com/fweinaug/system_settings/issues/31

**Comment by SuhailFoodCloud** [comment]
Hi @ced1check , 
Did you get a way to open the OS app settings using this package?
I am getting this error - 
`Unhandled Exception: MissingPluginException(No implementation found for method openSettings on channel com.spencerccf.app_settings/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)`

**Comment by ced1check** [comment]
> Hi @ced1check , Did you get a way to open the OS app settings using this package? I am getting this error - `Unhandled Exception: MissingPluginException(No implementation found for method openSettings on channel com.spencerccf.app_settings/methods) #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)`

I'm using system_settings, on which I created a PR. However it doesn't seem to be maintained anymore.

As for your exception, you might want to try to do a flutter clean ; flutter pub get
