### ISSUE TITLE
No implementation found for method openSettingsPanel

### ISSUE THREAD

**Issue by YueLiXing** [spencerccf/app_settings#207]
5.1.1 ios 

```
AppSettings.openAppSettingsPanel(AppSettingsPanelType.wifi);


[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method openSettingsPanel on channel com.spencerccf.app_settings/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
```

[testflutter_1.zip](https://github.com/spencerccf/app_settings/files/13547888/testflutter_1.zip)

**Comment by navaronbracke** [comment]
Application settings panels are an Android Q feature and are not available on iOS.

https://developer.android.com/reference/android/provider/Settings.Panel

**Comment by asadbekdev** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method openSettingsPanel on channel com.spencerccf.app_settings/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)

Same error

**Comment by navaronbracke** [comment]
@asadbekdev As I said above, the `Settings Panel` API is Android only.

**Comment by ChristineWasike** [comment]
@navaronbracke  What is the iOS alternative for this?

**Comment by navaronbracke** [comment]
I'm not sure if iOS has a similar API at all. If you find a reference to such an API, please let me now.

**Comment by ChristineWasike** [comment]
Will do, thanks!

**Comment by YueLiXing** [comment]
App-Prefs:Bluetooth
App-Prefs:WIFI
还是可以跳转到相关页面的
