### ISSUE TITLE
MissingPluginException(No implementation found for method location on channel app_settings)

### ISSUE THREAD

**Issue by pavel-birdy** [spencerccf/app_settings#28]
I'm getting exception. I don't know what I am doing wrong here. API seems pretty straight forward.

```dart
  Future<void> checkGpsConnection() async {
    bool isLocationEnabled = await Geolocator().isLocationServiceEnabled();
    if (!isLocationEnabled) {
      showDialog(
        context: context,
        builder: (context) => AlertDialog(
          title: Text('No GPS'),
          actions: <Widget>[
            FlatButton(
              child: Text('Open Settings'),
              onPressed: () async => await AppSettings.openLocationSettings(),
            )
          ],
        ),
      );
    }
  }
```

```
E/flutter (27329): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method location on channel app_settings)
E/flutter (27329): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (27329): <asynchronous suspension>
E/flutter (27329): #1      AppSettings.openLocationSettings (package:app_settings/app_settings.dart:15:14)
E/flutter (27329): <asynchronous suspension>
E/flutter (27329): #2      _MapsScreenState.checkGpsConnection.<anonymous closure>.<anonymous closure> (package:task_app/maps/maps_screen.dart:110:56)
E/flutter (27329): <asynchronous suspension>
E/flutter (27329): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (27329): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (27329): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (27329): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (27329): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (27329): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (27329): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (27329): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (27329): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (27329): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (27329): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (27329): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (27329): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (27329): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (27329): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (27329): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (27329): #19     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (27329): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

**Comment by badaween-ahmed** [comment]
oops! I just needed to pop the `AlertDialog()` before I call `AppSettings.openLocationSettings()`

**Comment by madd-project** [comment]
@pavel-birdy  haha, that was so funny. 😃

**Comment by madd-project** [comment]
Can you Provide the Code, that worked for you? I am getting same errrors.

**Comment by VictorLekweuwa** [comment]
I'm facing the same issue. Is there a fix for this?

**Comment by pavel-birdy** [comment]
I actually don't remember this issue I failed to provide any help.

> oops! I just needed to pop the `AlertDialog()` before I call `AppSettings.openLocationSettings()`

from here I can only guess that, I added `Navigator.of(context).pop()` before `AppSettings.openLocationSettings()`.
